theme = "onedark"

[editor]
line-number = "relative"
mouse = true
auto-pairs = false
auto-format = true
rulers = [80, 120]
bufferline = "always"




[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "bar"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "spinner", "version-control"]
center = ["file-name", "file-modification-indicator", "position-percentage"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.file-picker]
hidden = false

[keys.normal]


[keys.insert]
j = { j = "normal_mode"}
"C-space" = "completion"

[editor.lsp]
display-messages = true
auto-signature-help = false
# display-inlay-hints = true